@startuml
...
== Чтение списка заказов из кэша ==
Operator -> MES_Page: запрос списка заказов
MES_Page -> MES_API: запрос списка заказов
MES_API -> Cache: запрос списка заказов из кэша
MES_API <- Cache: ответ со списком заказов из кэша
MES_Page <- MES_API: ответ со списком заказов
Operator <- MES_API: ответ со списком заказов
...
== Запись списка заказов через кэш ==
Operator -> MES_Page: запись списка заказов
MES_Page -> MES_API: запись списка заказов
MES_API -> DB: запись списка заказов
DB -> MES_API: потверждение записи списка заказов 
MES_API -> MES_Page: потверждение записи списка заказов 
MES_Page -> Operator: потверждение записи списка заказов 
DB -> Cache: обновление данных кэша по изменению данных (инвалидация)
...
@enduml

